version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POLYGON_API_KEY="mqJl50msy2bOXpEVFjgNeYpCbsu0zo3f"
    depends_on:
      - redis
  redis:
  image: "redis:latest"
