version: "3.8"
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_URL=redis://redis:6379/1
    # volumes:
    #   - ./redis.conf:/usr/local/etc/redis/redis.conf
    

  # redis-slave:
  #   image: redis:latest
  #   container_name: redis-slave
  #   restart: always
  #   ports:
  #     - 6479:6379
  #   command: redis-server --slaveof redis-master 6379
  flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      - POLYGON_API_KEY="mqJl50msy2bOXpEVFjgNeYpCbsu0zo3f"
      - SQL_HOST=sqlite
    depends_on:
      - redis

  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - APP=/app/api/main.py
    command: python3 ./app/api/main.py
    depends_on:
      - redis
volumes:
  redis-master:
  # redis-slave:
# networks:
#   app-network:
#     driver: bridge
